### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by vicky5124** [AriusX7/serenity-utils#4]
- [x] Update to serenity 0.10
- [x] Update to tokio 1.0

**Comment by AriusX7** [comment]
#5 closes this.

**Comment by vicky5124** [comment]
@AriusX7 #5 increases a sub version, but having tokio 1.0 and serenity 0.10 as a dependency makes this change breaking, so the version should be bumped to 0.6.0

**Comment by AriusX7** [comment]
Fair enough, I'll fix that. Thank you for pointing that out.
